version: '3'
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - postgres
    build: .
    ports:
      - "3500:3500"